all:
  children:
    ims_servers:
      hosts:
        ims-node-1:
          ansible_host: 192.168.1.10
        ims-node-2:
          ansible_host: 192.168.1.11
      vars:
        ansible_user: admin
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
